resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: "tls_sds"
    tls_certificate:
      certificate_chain:
        filename: "/certs/effective-certs/envoy-client.pem"
      private_key:
        filename: "/certs/effective-certs/envoy-client-key.pem"
      watched_directory:
        path: "/certs"
